# Generated by Django 5.2.6 on 2025-09-09 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks_app', '0002_alter_tasks_deadline_alter_tasks_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='deadline',
            field=models.DateField(),
        ),
    ]
