# Generated by Django 5.2.6 on 2025-09-09 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks_app', '0003_alter_tasks_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='username',
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
