# Generated by Django 5.2.6 on 2025-09-09 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks_app', '0004_alter_users_username'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tasks',
            new_name='Task',
        ),
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
    ]
